# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:
  #schedule:
  #- cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ${{ matrix.os }}
    #strategy:
      #matrix:
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        #java_version: ['8', '11', '17']
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        #java-version: ${{ matrix.java_version }}
        #distribution: 'temurin'
        distribution: 'corretto'
        cache: maven
    #- name: PMD Code Analysis
      #id: pmd
      #uses: pmd/pmd-github-action@v1
      #with:
        #version: '6.40.0'
        #sourcePath: 'src/main/java'
        #rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
        #analyzeModifiedFilesOnly: false

    - name: Checkstyle Code Analysis
    
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      #if: github.event_name == 'push'
      run: |
        mvn -B package --file pom.xml
        
    - name: Junit Tests with Maven
      run: |
        mvn clean test
        
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
